# $Id$

dns:
  class: IN
  debug: 0
  ipv4: 1
  ipv6: 1
  retrans: 2
  retry: 3
  tcp_timeout: 5
  udp_timeout: 5
# perl -MMIME::Base64 -MStorable=freeze -MDNSCheck -le '$tmp=encode_base64(freeze(DNSCheck->new->resolver->get_preload_data));$tmp=~s/\n//g;print $tmp;'
  rootdata: BAcIMTIzNDU2NzgECAgIAwIAAAAEAwEAAAAEAw0AAAAIgRMAAABjLnJvb3Qtc2VydmVycy5uZXQuCIETAAAAay5yb290LXNlcnZlcnMubmV0LgiBEwAAAGUucm9vdC1zZXJ2ZXJzLm5ldC4IgRMAAABpLnJvb3Qtc2VydmVycy5uZXQuCIETAAAAYS5yb290LXNlcnZlcnMubmV0LgiBEwAAAGwucm9vdC1zZXJ2ZXJzLm5ldC4IgRMAAABkLnJvb3Qtc2VydmVycy5uZXQuCIETAAAAbS5yb290LXNlcnZlcnMubmV0LgiBEwAAAGgucm9vdC1zZXJ2ZXJzLm5ldC4IgRMAAABqLnJvb3Qtc2VydmVycy5uZXQuCIETAAAAZy5yb290LXNlcnZlcnMubmV0LgiBEwAAAGIucm9vdC1zZXJ2ZXJzLm5ldC4IgRMAAABmLnJvb3Qtc2VydmVycy5uZXQuAQAAAC4CAAAAbnMEAw0AAAAEAwEAAAAIgQsAAAAxOTIuMzMuNC4xMhMAAABjLnJvb3Qtc2VydmVycy5uZXQuBAMCAAAACIEMAAAAMTkzLjAuMTQuMTI5CIEUAAAAMjAwMTo3ZmQ6MDowOjA6MDowOjETAAAAay5yb290LXNlcnZlcnMubmV0LgQDAgAAAAiBFQAAADIwMDE6N2ZlOjA6MDowOjA6MDo1MwiBDQAAADE5Mi4zNi4xNDguMTcTAAAAaS5yb290LXNlcnZlcnMubmV0LgQDAQAAAAiBDgAAADE5Mi4yMDMuMjMwLjEwEwAAAGUucm9vdC1zZXJ2ZXJzLm5ldC4EAwIAAAAIgQoAAAAxOTguNDEuMC40CIEYAAAAMjAwMTo1MDM6YmEzZTowOjA6MDoyOjMwEwAAAGEucm9vdC1zZXJ2ZXJzLm5ldC4EAwEAAAAIgQsAAAAxMjguOC4xMC45MBMAAABkLnJvb3Qtc2VydmVycy5uZXQuBAMCAAAACIELAAAAMTk5LjcuODMuNDIIgRUAAAAyMDAxOjUwMDozOjA6MDowOjA6NDITAAAAbC5yb290LXNlcnZlcnMubmV0LgQDAgAAAAiBFQAAADIwMDE6ZGMzOjA6MDowOjA6MDozNQiBDAAAADIwMi4xMi4yNy4zMxMAAABtLnJvb3Qtc2VydmVycy5uZXQuBAMCAAAACIEZAAAAMjAwMTo1MDA6MTowOjA6MDo4MDNmOjIzNQiBCwAAADEyOC42My4yLjUzEwAAAGgucm9vdC1zZXJ2ZXJzLm5ldC4EAwIAAAAIgQ0AAAAxOTIuNTguMTI4LjMwCIEXAAAAMjAwMTo1MDM6YzI3OjA6MDowOjI6MzATAAAAai5yb290LXNlcnZlcnMubmV0LgQDAQAAAAiBDAAAADE5Mi4xMTIuMzYuNBMAAABnLnJvb3Qtc2VydmVycy5uZXQuBAMBAAAACIEOAAAAMTkyLjIyOC43OS4yMDETAAAAYi5yb290LXNlcnZlcnMubmV0LgQDAgAAAAiBFQAAADIwMDE6NTAwOjJmOjA6MDowOjA6ZgiBCwAAADE5Mi41LjUuMjQxEwAAAGYucm9vdC1zZXJ2ZXJzLm5ldC4DAAAAaXBz

logging:
  interactive: 0
  locale: ~

smtp:
  enable: 1
  hostname: ~
  timeout: 20

net:
    ipv4: 1
    ipv6: 1
    smtp: 1
    v4root: 
        - origin.asnlookup.iis.se
        - origin.asn.cymru.com
    v6root: 
        - origin6.asnlookup.iis.se
        - origin6.asn.cymru.com

syslog:
    ident: dnscheck
    facility: local2

daemon:
    pidfile: /var/tmp/dnscheck_dispatcher.pid
    errorlog: /var/tmp/dnscheck_errors.log
    maxchild: 20
    geoip: /opt/local/share/GeoIP/GeoLiteCity.dat
    user: called

# This information is expected to be overridden in site_config.yaml
# Not all keys will be useful for all setups. See the documentation
# for the various programs about which keys they use, and what they
# mean. Some info is in DNSCheck::Overview.

dbi:
    host: 127.0.0.1
    port: 3306
    database: dnscheckng
    user: root
    password: HurSv4rtKanDetBli

couchdb:
   url: http://127.0.0.1:5984/
   username: ~
   password: ~

#couchdb:
#   url: http://willow.faerywicca.se:5984/
#   username: calle
#   password: foobar

# reggie:
#     host: 127.0.0.1
#     port: 13317
#     database: reggie
#     user: reggieuser
#     password: not_given_here

12hour:
    smtphost: smtp.example.com
    from: unknown@example.com
    subject: Problem(s) in your domain(s)
    timespan: 24:00:00
    debug: 1
    sourcestring: 12-hour-check

zonediff:
    datafile: /tmp/zone_hashes.txt
    servers:
      - ns1.example.com
      - ns2.example.com
      - ns3.example.com
    domain: example.com.
    tsig: test.key TSIG WW91IGFjdHVhbGx5IGJvdGhlcmVkIHRvIGRlY29kZSB0aGlzPw==
    sourcestring: 12-hour-check
    flagdomain:
        - 000000000000.example.com
        - zzzzzzzzzzzz.example.com

nsdiff:
    datafile: /tmp/zone_ns.txt
    servers:
      - ns1.example.com
      - ns2.example.com
      - ns3.example.com
    domain: example.com.
    tsig: test.key TSIG WW91IGFjdHVhbGx5IGJvdGhlcmVkIHRvIGRlY29kZSB0aGlzPw==
    flagdomain:
        - 000000000000.example.com
        - zzzzzzzzzzzz.example.com

twitterbot:
        datafile: /var/tmp/twitterbot.db
        username: dnscheck
        password: foobar

zonestat:
        pageanalyzer: /Users/called/Clients/IIS/pageanalyzer
        python: /opt/local/bin/python
        sslscan: /Users/called/Clients/IIS/sslscan-win/sslscan
        openssl: /opt/local/bin/openssl
        cacertfile: /opt/local/share/dnscheck/cacerts.pem

zone:
    datafile: /var/tmp/se.zone
