# $Id$

dns:
  debug: 0
  ipv4: 1
  ipv6: 1
  class: IN
  udp_timeout: 5
  tcp_timeout: 5
  retry: 3
  retrans: 2

smtp:
  enable: 1
  #hostname: xyzzy
  timeout: 20

logging:
 interactive: 0

engine:
  processes: 1
  chunksize: 10
  gnore_debug: 0
  mysql_file: /etc/my.cnf
  mysql_group: dnscheck
  #syslog_facility: daemon
  #prio_low: undef
  #prio_high: undef
