# $Id$

dns:
  class: IN
  debug: 0
  ipv4: 1
  ipv6: 1
  retrans: 2
  retry: 3
  tcp_timeout: 5
  udp_timeout: 5

logging:
  interactive: 0
  locale: ~

smtp:
  enable: 1
  hostname: ~
  timeout: 20

net:
    ipv4: 1
    ipv6: 1
    smtp: 1

syslog:
    ident: dnscheck
    facility: local2

daemon:
    pidfile: /var/run/dnscheck_dispatcher.pid
    errorlog: /var/log/dnscheck_errors.log
    maxchild: 10

# This information is expected to be overridden in site_config.yaml
dbi:
    host: 127.0.0.1
    port: 13317
    database: dnscheckng
    user: dnscheckng
    password: not_given_here
